### ISSUE TITLE
Tracking issue for v0.3.0 deprecations

### ISSUE THREAD

**Issue by tc85324** [gchq/coreax#578]
### What's the issue?

The following are deprecated, for removal in the v0.3.0 release

- [ ] `coreax.weights.SBQ` -> replaced by `SBQWeightsOptimiser`
- [ ] `coreax.weights.MMD` -> replaced by `MMDWeightsOptimiser`
- [ ] `coreax.util.squared_distance_pairwise` -> replaced by `pairwise(squared_distance)`
- [ ] `coreax.util.pairwise_difference` -> replaced by `pairwise(difference)`
